In [1]:
#numpy
import numpy as np

In [130]:
a=([1, 2, 3, 3, 1],[6, 8, 11, 10, 7])
a = ([1,6],
    [2,8],
    [3,11],
    [3,10],
    [1,7])
a = np.array(a)

a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [131]:
#1

# mean_a = [np.mean(a[0]),np.mean(a[1])]
mean_a=np.mean(a, axis=0)


np.shape(a)
mean_a

array([2. , 8.4])

In [132]:
# 2

a_centered = a - mean_a

np.shape(a_centered)

(5, 2)

In [133]:
#3
a_centered = np.transpose(a_centered)
print(a_centered)

a_centered_sp = np.dot(a_centered[0],a_centered[1]) / (len(a_centered[0])-1)
a_centered_sp

[[-1.   0.   1.   1.  -1. ]
 [-2.4 -0.4  2.6  1.6 -1.4]]


2.0

In [134]:
#4
a = a.transpose()
m = np.cov(a)
m[0,1]

2.0

In [65]:
#pandas
#1
import pandas as pd
import numpy as np

# Задание 1
# Импортируйте библиотеку Pandas и дайте ей псевдоним pd. 
# Создайте датафрейм authors со столбцами author_id и author_name,
# в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
# Затем создайте датафрейм book cо столбцами author_id, book_title и price, 
# в которых соответственно содержатся данные:  



In [25]:
authors_data = {
    "author_id": [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']
}

authors = pd.DataFrame(authors_data)

book_data = {
'author_id': [1, 1, 1, 2, 2, 3, 3],
'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
'price': [450, 300, 350, 500, 450, 370, 290]}
book = pd.DataFrame(book_data)



In [26]:
# Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

merged_df = pd.merge(authors, book, on='author_id', how='outer')

merged_df

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [27]:
top5 = merged_df.nlargest(5, "price")

top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [58]:
# Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
# author_name, min_price, max_price и mean_price,
# в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.



authors_stat = (merged_df.set_index('author_name')
   .groupby(level=0)['price']
   .agg(mean_price= 'mean', max_price = "max",min_price = "min")
)
authors_stat

mean_price  max_price  min_price
author_name                                  
Островский   330.000000        370        290
Тургенев     366.666667        450        300
Чехов        475.000000        500        450

In [73]:
cover = pd.DataFrame({'cover':['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']})


df = pd.concat([merged_df, cover], axis=1)
df

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [71]:
# Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут 
# располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
# ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
# Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.
# Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. 
# Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая",
# а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости 
# загрузите библиотеку Numpy.
# Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl".
# Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [68]:
?pd.pivot_table

In [76]:
book_info = pd.pivot_table(df, values = 'price', index =["author_name"],
                        columns=['cover'],aggfunc=np.sum, fill_value=0)

book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [77]:
book_info.to_pickle('book_info.pkl')

In [79]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950